### ISSUE TITLE
Does this mod work in linux?

### ISSUE THREAD

**Issue by sieira** [itsmecodyp/WorldBox#1]
I'm getting 
```
FileNotFoundException: Could not load file or assembly 'Facepunch.Steamworks.Win64, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
```

**Comment by sieira** [comment]
Nevermind, It all seems to work regardless of the error

**Comment by itsmecodyp** [comment]
Hey, that's a file that comes with windows versions of the game and hooks into steam. Simplegui uses it to ID users and collect a bit of data. Like you mentioned already, it shouldn't impact users on other platforms (linux/mac), that bit of the mod just wont work

I'd have to build platform specific versions using the right reference, and I'm not too worried about that

Thanks for the report though! First time someones made an issue here haha
